version: '3'
services:

  db:
    image: e-que-ha-db:1.0
    restart: always
    ports: 
      - '5432:5432'

  front-end:
    image: e-que-ha-fe:1.0
    restart: always
    ports:
      - '8080:5000'

  back-end:
    image: e-que-ha-be:1.0
    restart: always
    ports:
      - '3342:3342'
